### PR TITLE
Display which selector caused the error

### PR DESCRIPTION
**Pull request by davidblurton**

### CODE REVIEW

**Comment by ben-eb** [comment]
@davidtheclark What do you think of being more descriptive with the error messages? I think this is what the patch is trying to achieve, but I think it might be nicer to show some error output that is like [postcss' CssSyntaxError](https://github.com/postcss/postcss/blob/master/lib/css-syntax-error.es6)

Perhaps we can get this in for 2.0?

**Comment by davidtheclark** [comment]
Might be nice, true. But couldn't we get 2.0 out before that?

**Comment by ben-eb** [comment]
Okay. Let's look at this for a minor release. 👍

**Comment by ben-eb** [comment]
@davidblurton Thanks, but we decided to throw a `CssSyntaxError` when a PostCSS rule node is passed as input, so you will receive more information when the parser finds a syntax error. 😄 

https://github.com/postcss/postcss-selector-parser/releases/tag/v3.0.0-rc.0

**Pull request closed without merging**
