### PR TITLE
Move `babel-eslint` to devDeps

### LINKED ISSUE #154: babel-eslint is installed as a dependency
Not a huge issue, but I've noticed many babel packages installed in my node_modules because of this dependency.

For the next release, can `babel-eslint` be moved to devDependencies? :)

### PR DESCRIPTION
**Pull request by AviVahl**
only used during development time, so it shouldn't be installed for users of library

closes #154

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@AviVahl Thanks!

**Comment by AviVahl** [comment]
@evilebottnawi any chance for a new rc with this merged?

**Comment by evilebottnawi** [comment]
@AviVahl maybe, need wait @chriseppstein @jonathantneal

**Comment by AviVahl** [comment]
btw, I've noticed several devDeps are outdated. would you accept PRs updating them a bit (I'm thinking babel 7, preset-env, etc)?

**Comment by jonathantneal** [comment]
@AviVahl, yes! Thank you.

**Pull request merged**
