### PR TITLE
docs: update clone

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Again, failed :confused:

**Comment by btea** [comment]
Same error as before, can you ignore it? Documentation changes seem to have no effect. (I don't know what to do 😅)

**Comment by btea** [comment]
The test passed after the merge 😕

**Comment by alexander-akait** [comment]
Yeah, because you use old version of your fork, so your branch was not up to day (with fix), just rebase fork :smile:

**Pull request merged**
