### PR TITLE
Add support for the nesting selector.

### PR DESCRIPTION
**Pull request by ben-eb**
/cc @jeddy3 @davidtheclark 

Ref: https://github.com/stylelint/stylelint/issues/499

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks for making at start on `2.0` :) It's looking great!

Would it be possible to get a test for `&string` (e.g. `&-foo`, `&_foo` or `&foo` (either here or in [`src/__tests__/tags.js`](https://github.com/postcss/postcss-selector-parser/blob/master/src/__tests__/tags.js) ? I'm assuming that those examples will be parsed as a `tag`s? But I'd like to be sure as we'll need to handle this [non-standard behaviour](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested_rules) (of allowing & to be used as a prefix) down stream.

**Comment by ben-eb** [comment]
Do those tests that I've added make sense?

**Comment by jeddy3** [comment]
Oops, I totally misunderstood how it'd work. Thanks for the tests. It's much clearer now :)

**Comment by davidtheclark** [comment]
Looks great!

**Pull request closed without merging**
