### PR TITLE
fix(types): clone parameter should be optional

### PR DESCRIPTION
**Pull request by btea**

### CODE REVIEW

**Comment by btea** [comment]
It looks like the reason for the test failing seems to be a timeout 🤔

**Comment by alexander-akait** [comment]
Can you investigate it? Sorry I don't have time on it, only merge and do release :disappointed:

**Comment by btea** [comment]
ok, I'll look into it later.

**Comment by btea** [comment]
According to the failure, it seems to be related to the node version. However, I installed the corresponding version (14) and then ran the test and everything seemed to be fine, and no valid information was obtained.😞

It may be related to the system. My machine is win11, and ci seems to be ubuntu. Maybe I should configure the relevant environment tomorrow and check again.

**Comment by alexander-akait** [comment]
Let's try to update test runner, maybe just a bug?

**Comment by btea** [comment]
What should I do?

**Comment by alexander-akait** [comment]
Try to update dev deps

**Comment by btea** [comment]
Run `npm update -D` to update all dependencies?

**Comment by alexander-akait** [comment]
Fixed https://github.com/postcss/postcss-selector-parser/pull/276 release will be soon

**Comment by btea** [comment]
ok, thank you for your hard work! I found that you deleted the package-lock.json file, so the previous test failure has something to do with this file?

**Comment by alexander-akait** [comment]
I don't delete it, just regenerate for v1, becaue v1 and v2 are incompatibility (don't know why npm command do this bad breaking change, and I think such things should never happen with package managers)

**Comment by btea** [comment]
ok, I see, thanks for your reply ❤️

**Pull request closed without merging**
