### PR TITLE
Throw on missing opening parenthesis.

### PR DESCRIPTION
**Pull request by ben-eb**
Ref: #42.

/cc @jeddy3

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks for addressing this so quickly!

Lgtm.

However, the original stylelint issue reporter [just mentioned](https://github.com/stylelint/stylelint/issues/848#issuecomment-192220782) that they also had trouble with square brackets. So, I quickly tested each of the chars from the tokenizer and the parser seems to hang a trailing `]` or `;`.

Am I right in thinking that the change here won't catch these two?

**Comment by ben-eb** [comment]
For semicolons, see: https://github.com/postcss/postcss-selector-parser/issues/27

No, it currently doesn't handle trailing `]`. Will update.

**Comment by jeddy3** [comment]
> Will update.

Thank you.

> For semicolons, see: #27

Actually, forget I mentioned semicolons... `a; {}` isn't valid CSS and isn't parsed by postcss itself, and so it should never reach the selector parser :)

FYI, [we used](https://github.com/stylelint/stylelint/pull/804/files) your approach in #27 for dealing with trailing colons across all our selector rules. So, thanks for that too :)

**Comment by ben-eb** [comment]
@jeddy3 Cool. :+1:

Updated to include square bracket checking.

**Comment by jeddy3** [comment]
Excellent! Lgtm. 

Can you release this as a patch, or will it need to be rolled into `2.0`?

**Comment by ben-eb** [comment]
Going to release as a patch as it's a fix, not a breaking change. :smiley:

**Comment by ben-eb** [comment]
Released in `1.3.3`.

**Pull request merged**
