### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by onigoetz**
Hello,

I am in the process of creating a few PRs to upgrade to PostCSS8 here and there.

This module doesn't need any special upgrade or breaking change, but since I was in the middle of it I thought I could still finish and send a PR.

This PR contains _no breaking change_ since everything changed is in tests or devDependencies.

Dev dependencies updates include : 

- Replace `eslint-plugin-babel` with `@babel/eslint-plugin`
- Replace `babel-eslint` with `@babel/eslint-parser`
- Upgrade from `ava` version 1 => 3
- Upgrade from `eslint` version 5 => 7
- Upgrade from `semver` version 5 => 7
- Upgrade from `postcss`version 7 => 8
- Upgrade from `del-cli`version 1 => 3

### CODE REVIEW

**Comment by onigoetz** [comment]
It seems that tests can't run on node 8 and fail with timeouts on 10 / 11

**Comment by evilebottnawi** [comment]
@onigoetz Feel free remove node@8 from matrix

**Comment by onigoetz** [comment]
Also node 6 ? should it also be updated in package.json ?

**Comment by evilebottnawi** [comment]
@onigoetz Late, not here

**Comment by evilebottnawi** [comment]
@onigoetz Do you need help?

**Comment by onigoetz** [comment]
Sorry I didn't send a message sooner.
It seems that the tests fail because of a timeout, I don't know exactly why and can't reproduce locally.

I could need help to figure that part out :)

**Comment by evilebottnawi** [comment]
Maybe just try increase timeout?

**Comment by onigoetz** [comment]
yes sure, I just wanted to make it the last resort, not the first thing I try

**Review by evilebottnawi — APPROVED** [review]
Thanks, ready to merge or something else?

**Comment by onigoetz** [comment]
I think it's all good

**Comment by evilebottnawi** [comment]
Thanks

**Pull request merged**
