### PR TITLE
Update Babel

### PR DESCRIPTION
**Pull request by jonathantneal**
It would be really sweet if we could also upgrade Babel before the next release. We can just give it a day or two; and if no one can solve it then I can roll it back and release 6 anyway.

### CODE REVIEW

**Comment by jonathantneal** [comment]
```
> postcss-selector-parser@6.0.0 pretest ~/GitHub/postcss/postcss-selector-parser
> eslint src


> postcss-selector-parser@6.0.0 test ~/GitHub/postcss/postcss-selector-parser
> nyc ava src/__tests__/*.js

~/GitHub/postcss/postcss-selector-parser/node_modules/@babel/traverse/lib/path/context.js:60
      throw new Error(`Unexpected return value from visitor method ${fn}`);
      ^

Error: Unexpected return value from visitor method function (path) {
          return fn.call(state, path, state);
        }
```

**Comment by evilebottnawi** [comment]
Weird, i think we should update `ava` first (to be honest i prefer `jest` :smile: )

**Comment by jonathantneal** [comment]
@evilebottnawi, ava changed how its `throw` works, and that would require us to update functions used by the tests. I chose not to take that on yet. Other than that, it’s just 2 snapshots that I had to update.

**Comment by evilebottnawi** [comment]
@jonathantneal what do you think about CI error?

**Comment by jonathantneal** [comment]
@evilebottnawi, I’ve restored the `package-lock.json` file.

After updating the babel dependencies in `package.json`, I deleted `package-lock.json` so that it could be regenerated. However, when the `prepare` script failed on `npm install`, it also failed to regenerate `package-lock.json`. I didn’t catch this. Thank you!

**Pull request closed without merging**
