### PR TITLE
Allow escaped dot within class name

### LINKED ISSUE #165: Classes with dot within
Hello,

I would like to kindly report a issue with parser. 

For given selector `.foo\.bar` (which is valid CSS selector afaik) parser outputs two `ClassName`s: `.foo` and `.bar`.

I think the expected output in this case is a single class.

Noticed same behaviour in v4 and v5

Peace :v:

### PR DESCRIPTION
**Pull request by plesiecki**
Fixes #165

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@jonathantneal i think time to release stable version

**Comment by jonathantneal** [comment]
I’ll try to package this later today. I’m rehearsing for another performance tomorrow and then I’m on vacation for 2 weeks.

**Comment by jonathantneal** [comment]
@evilebottnawi I agree

**Comment by evilebottnawi** [comment]
@jonathantneal :+1: , good vacation :star:

**Pull request merged**
